<?php


use Phinx\Seed\AbstractSeed;

class MitemKanrisSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $data = [

            [
                'id' => 1,
                'group_cd' => 'employeement_status',
                'name' => '雇用形態',
                'kana' => 'コヨウケイタイ',
                'ryaku' => '雇用形態',
                'function_division' => 1,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 1,
            ],
            [
                'id' => 2,
                'group_cd' => 'transpotation',
                'name' => '交通手段',
                'kana' => 'コウツウシュダン',
                'ryaku' => '交通手段',
                'function_division' => 1,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 2,
            ],
            [
                'id' => 3,
                'group_cd' => 'account_type',
                'name' => '口座種別',
                'kana' => 'コウザシュベツ',
                'ryaku' => '口座種別',
                'function_division' => 1,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 3,
            ],
            [
                'id' => 4,
                'group_cd' => 'account_subjects',
                'name' => '基本科目',
                'kana' => 'キホンカモク',
                'ryaku' => '基本科目',
                'function_division' => 3,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 4,
            ],
            [
                'id' => 5,
                'group_cd' => 'account_dt_subjects',
                'name' => '明細科目',
                'kana' => 'メイサイカモク',
                'ryaku' => '明細科目',
                'function_division' => 3,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 5,
            ],
            [
                'id' => 6,
                'group_cd' => 'when_holiday',
                'name' => '支払日祝日',
                'kana' => 'シュクジツ',
                'ryaku' => '支払日祝日',
                'function_division' => 3,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 6,
            ],
            [
                'id' => 7,
                'group_cd' => 'health_insurance',
                'name' => '健康保険組合',
                'kana' => 'ホケン',
                'ryaku' => '健康保険組合',
                'function_division' => 3,
                'kbn_1' => '組合名',
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 7,
            ],
            [
                'id' => 8,
                'group_cd' => 'psj_todoke_kubun',
                'name' => '届出区分',
                'kana' => '届出区分',
                'ryaku' => '届出区分',
                'function_division' => 2,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 8,
            ],
            [
                'id' => 9,
                'group_cd' => 'kengen_group',
                'name' => '権限グループ',
                'kana' => 'ケンゲングループ',
                'ryaku' => '権限グループ',
                'function_division' => 1,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 12,
            ], [
                'id' => 10,
                'group_cd' => 'psj_sosiki',
                'name' => '組織',
                'kana' => '組織',
                'ryaku' => '組織',
                'function_division' => 2,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 0,
            ],
            [
                'id' => 11,
                'group_cd' => 'ot_code',
                'name' => 'Làm thêm',
                'kana' => 'Làm thêm',
                'ryaku' => 'Làm thêm',
                'function_division' => 2,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 0,
            ],
            [
                'id' => 12,
                'group_cd' => 'transfer_code',
                'name' => 'Làm bù nghỉ bù',
                'kana' => 'Làm bù nghỉ bù',
                'ryaku' => 'Làm bù nghỉ bù',
                'function_division' => 2,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 0,
            ],
            [
                'id' => 13,
                'group_cd' => 'psj_account_level',
                'name' => 'Cấp bậc',
                'kana' => 'Cấp bậc',
                'ryaku' => 'Cấp bậc',
                'function_division' => 2,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 0,
            ],

            [
                'id' => 14,
                'group_cd' => 'shift_change',
                'name' => 'Đổi giờ làm',
                'kana' => 'Đổi giờ làm',
                'ryaku' => 'Đổi giờ làm',
                'function_division' => 2,
                'kbn_1' => null,
                'kbn_2' => null,
                'kbn_3' => null,
                'kbn_4' => null,
                'kbn_5' => null,
                'label1' => null,
                'label2' => null,
                'label3' => null,
                'label4' => null,
                'label5' => null,
                'text_label_1' => null,
                'order_no' => 0,
            ],
        ];

        $table = $this->table('m_item_kanris');
        $table->truncate();
        $table->insert($data)->save();
    }
}
