<?php


use Phinx\Seed\AbstractSeed;

class MitemSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $data = [
            [
                'item_group_cd' => 'kengen_group',
                'item_cd' => 'admin',
                'item_name' => 'システム管理者',
                'item_kana' => 'システムカンリシャ',
                'item_ryaku' => 'システム管理者',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],

            [
                'item_group_cd' => 'kengen_group',
                'item_cd' => 'leader',
                'item_name' => 'リーダー',
                'item_kana' => 'leader',
                'item_ryaku' => 'leader',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 10,
            ],
            [
                'item_group_cd' => 'kengen_group',
                'item_cd' => 'user',
                'item_name' => '一般',
                'item_kana' => 'イッパン',
                'item_ryaku' => '一般',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 5,
            ],
            [
                'item_group_cd' => 'when_holiday',
                'item_cd' => '1',
                'item_name' => '前',
                'item_kana' => 'ゼン',
                'item_ryaku' => '前',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'when_holiday',
                'item_cd' => '2',
                'item_name' => '翌',
                'item_kana' => 'ヨク',
                'item_ryaku' => '翌',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 3,
            ],
            [
                'item_group_cd' => 'health_insurance',
                'item_cd' => '01130012',
                'item_name' => '全国健康保険協会　東京支部',
                'item_kana' => 'キョウカイケンポ',
                'item_ryaku' => '全国健康保険協会　東京支部',
                'item_kbn_1' => '全国健康保険協会',
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'health_insurance',
                'item_cd' => '01330018',
                'item_name' => '全国健康保険協会　岡山支部',
                'item_kana' => 'キョウカイケンポ',
                'item_ryaku' => '全国健康保険協会　岡山支部',
                'item_kbn_1' => '全国健康保険協会',
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 2,
            ],
            [
                'item_group_cd' => 'health_insurance',
                'item_cd' => '01340017',
                'item_name' => '全国健康保険協会　広島支部',
                'item_kana' => 'キョウカイケンポ',
                'item_ryaku' => '全国健康保険協会　広島支部',
                'item_kbn_1' => '全国健康保険協会',
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 3,
            ],
            [
                'item_group_cd' => 'health_insurance',
                'item_cd' => '06139166',
                'item_name' => 'ひかり健康保険組合',
                'item_kana' => 'ヒカリケンポ',
                'item_ryaku' => 'ひかり健康保険組合',
                'item_kbn_1' => 'ひかり健康保険組合',
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 4,
            ],


            [
                'item_group_cd' => 'employeement_status',
                'item_cd' => '1',
                'item_name' => 'アルバイト・パート',
                'item_kana' => '',
                'item_ryaku' => 'アルバイト・パート',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 41,
            ],
            [
                'item_group_cd' => 'employeement_status',
                'item_cd' => '2',
                'item_name' => 'クルー',
                'item_kana' => '',
                'item_ryaku' => 'クルー',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 42,
            ],
            [
                'item_group_cd' => 'employeement_status',
                'item_cd' => '3',
                'item_name' => '正社員',
                'item_kana' => '',
                'item_ryaku' => '正社員',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 43,
            ],

            [
                'item_group_cd' => 'tax_kbn',
                'item_cd' => '2',
                'item_name' => '非課税',
                'item_kana' => '',
                'item_ryaku' => '非課税',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 64,
            ],
            [
                'item_group_cd' => 'tax_kbn',
                'item_cd' => '1',
                'item_name' => '課税',
                'item_kana' => '',
                'item_ryaku' => '課税',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 65,
            ],

            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '1',
                'item_name' => '諸会費',
                'item_kana' => '',
                'item_ryaku' => '諸会費',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 71,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '2',
                'item_name' => 'FINTECH仕入',
                'item_kana' => '',
                'item_ryaku' => 'FINTECH仕入',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 72,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '3',
                'item_name' => 'リース料',
                'item_kana' => '',
                'item_ryaku' => 'リース料',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 73,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '4',
                'item_name' => '仮払金',
                'item_kana' => '',
                'item_ryaku' => '仮払金',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 74,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '5',
                'item_name' => '支払手数料',
                'item_kana' => '',
                'item_ryaku' => '支払手数料',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 75,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '6',
                'item_name' => '少額償却資産',
                'item_kana' => '',
                'item_ryaku' => '少額償却資産',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 76,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '7',
                'item_name' => '前払費用',
                'item_kana' => '',
                'item_ryaku' => '前払費用',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 77,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '8',
                'item_name' => '地代家賃',
                'item_kana' => '',
                'item_ryaku' => '地代家賃',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 78,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '9',
                'item_name' => '売掛金',
                'item_kana' => '',
                'item_ryaku' => '売掛金',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 79,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '10',
                'item_name' => '敷金',
                'item_kana' => '',
                'item_ryaku' => '敷金',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 80,
            ],
            [
                'item_group_cd' => 'account_subjects',
                'item_cd' => '11',
                'item_name' => '未払金',
                'item_kana' => '',
                'item_ryaku' => '未払金',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 81,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '1',
                'item_name' => 'その他',
                'item_kana' => '',
                'item_ryaku' => 'その他',
                'item_kbn_1' => null,
                'item_kbn_2' => '5',
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 82,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '2',
                'item_name' => 'HG',
                'item_kana' => '',
                'item_ryaku' => 'HG',
                'item_kbn_1' => null,
                'item_kbn_2' => '1',
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 83,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '3',
                'item_name' => 'ONEtoONE',
                'item_kana' => '',
                'item_ryaku' => 'ONEtoONE',
                'item_kbn_1' => null,
                'item_kbn_2' => '1',
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 84,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '4',
                'item_name' => 'カード端末',
                'item_kana' => '',
                'item_ryaku' => 'カード端末',
                'item_kbn_1' => null,
                'item_kbn_2' => '5',
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 85,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '5',
                'item_name' => '外国送金手数料',
                'item_kana' => '',
                'item_ryaku' => '外国送金手数料',
                'item_kbn_1' => null,
                'item_kbn_2' => '3',
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 86,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '6',
                'item_name' => '車両リース',
                'item_kana' => '',
                'item_ryaku' => '車両リース',
                'item_kbn_1' => null,
                'item_kbn_2' => '3',
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 87,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '7',
                'item_name' => '仲介手数料',
                'item_kana' => '',
                'item_ryaku' => '仲介手数料',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 88,
            ],
            [
                'item_group_cd' => 'account_dt_subjects',
                'item_cd' => '8',
                'item_name' => '駐車場家賃',
                'item_kana' => '',
                'item_ryaku' => '駐車場家賃',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 89,
            ],

            [
                'item_group_cd' => 'contract_flag',
                'item_cd' => '1',
                'item_name' => '入居中',
                'item_kana' => '',
                'item_ryaku' => '入居中',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 94,
            ],

            [
                'item_group_cd' => 'transfer__code',
                'item_cd' => '23',
                'item_name' => 'その他',
                'item_kana' => null,
                'item_ryaku' => 'その他',
                'item_kbn_1' => null,
                'item_kbn_2' => '5',
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 82,
            ],
            [
                'item_group_cd' => 'transfer__code',
                'item_cd' => '21',
                'item_name' => '総合',
                'item_kana' => 'ソウゴウ',
                'item_ryaku' => '総合',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'transfer__code',
                'item_cd' => '11',
                'item_name' => '給与',
                'item_kana' => 'キュウヨ',
                'item_ryaku' => '給与',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 2,
            ],
            [
                'item_group_cd' => 'transfer__code',
                'item_cd' => '12',
                'item_name' => '賞与',
                'item_kana' => 'ショウヨ',
                'item_ryaku' => '賞与',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 3,
            ],

//            [
//                'item_group_cd' => 'psj_todoke_kubun',
//                'item_cd' => 'TS',
//                'item_name' => '遅刻早退',
//                'item_kana' => '遅刻早退',
//                'item_ryaku' => '遅刻早退',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'psj_todoke_kubun',
//                'item_cd' => 'SG',
//                'item_name' => '私用外出',
//                'item_kana' => '私用外出',
//                'item_ryaku' => '私用外出',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'psj_todoke_kubun',
//                'item_cd' => 'YRK',
//                'item_name' => '有給休暇',
//                'item_kana' => '有給休暇',
//                'item_ryaku' => '有給休暇',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'psj_todoke_kubun',
//                'item_cd' => 'MRK',
//                'item_name' => '無給休暇',
//                'item_kana' => '無給休暇',
//                'item_ryaku' => '無給休暇',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'psj_todoke_kubun',
//                'item_cd' => 'TKK',
//                'item_name' => '特別休暇',
//                'item_kana' => '特別休暇',
//                'item_ryaku' => '特別休暇',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'psj_todoke_kubun',
//                'item_cd' => 'DJK',
//                'item_name' => '独自休暇',
//                'item_kana' => '独自休暇',
//                'item_ryaku' => '独自休暇',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'psj_todoke_kubun',
//                'item_cd' => 'KK',
//                'item_name' => '欠勤',
//                'item_kana' => '欠勤',
//                'item_ryaku' => '欠勤',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],

//            [
//                'item_group_cd' => 'ot_code',
//                'item_cd' => 'ZG',
//                'item_name' => '普通残業',
//                'item_kana' => '普通残業',
//                'item_ryaku' => '普通残業',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'ot_code',
//                'item_cd' => 'ZGK',
//                'item_name' => '休日残業',
//                'item_kana' => '休日残業',
//                'item_ryaku' => '休日残業',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
//            [
//                'item_group_cd' => 'ot_code',
//                'item_cd' => 'ZGY',
//                'item_name' => '深夜残業',
//                'item_kana' => '深夜残業',
//                'item_ryaku' => '深夜残業',
//                'item_kbn_1' => null,
//                'item_kbn_2' => null,
//                'item_kbn_3' => null,
//                'item_kbn_4' => null,
//                'item_kbn_5' => null,
//                'item_num_1' => null,
//                'item_num_2' => null,
//                'item_num_3' => null,
//                'item_num_4' => null,
//                'item_num_5' => null,
//                'item_text_1' => null,
//                'order_no' => 1,
//            ],
            [
                'item_group_cd' => 'ot_code',
                'item_cd' => 'OTD1',
                'item_name' => 'Làm thêm ngày thường',
                'item_kana' => 'Làm thêm ngày thường',
                'item_ryaku' => 'Làm thêm ngày thường',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'ot_code',
                'item_cd' => 'OTN1',
                'item_name' => 'Làm thêm đêm ngày thường',
                'item_kana' => 'Làm thêm đêm ngày thường',
                'item_ryaku' => 'Làm thêm đêm ngày thường',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'ot_code',
                'item_cd' => 'OTD2',
                'item_name' => 'Làm thêm ngày nghỉ',
                'item_kana' => 'Làm thêm ngày nghỉ',
                'item_ryaku' => 'Làm thêm ngày nghỉ',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'ot_code',
                'item_cd' => 'OTN2',
                'item_name' => 'Làm thêm đêm ngày nghỉ',
                'item_kana' => 'Làm thêm đêm ngày nghỉ',
                'item_ryaku' => 'Làm thêm đêm ngày nghỉ',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'ot_code',
                'item_cd' => 'OTD3',
                'item_name' => 'Làm thêm ngày nghỉ lễ',
                'item_kana' => 'Làm thêm ngày nghỉ lễ',
                'item_ryaku' => 'Làm thêm ngày nghỉ lễ',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'ot_code',
                'item_cd' => 'OTN3',
                'item_name' => 'Làm thêm đêm ngày nghỉ lễ',
                'item_kana' => 'Làm thêm đêm ngày nghỉ lễ',
                'item_ryaku' => 'Làm thêm đêm ngày nghỉ lễ',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'transfer_code',
                'item_cd' => 'FKK',
                'item_name' => '振替休暇',
                'item_kana' => '振替休暇',
                'item_ryaku' => '振替休暇',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'shift_change',
                'item_cd' => 'STT',
                'item_name' => 'Đổi giờ làm',
                'item_kana' => 'Đổi giờ làm',
                'item_ryaku' => 'Đổi giờ làm',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_todoke_kubun',
                'item_cd' => 'OFF1',
                'item_name' => 'Nghỉ có lương',
                'item_kana' => 'Nghỉ có lương',
                'item_ryaku' => 'Nghỉ có lương',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_todoke_kubun',
                'item_cd' => 'OFF2',
                'item_name' => 'Nghỉ không lương',
                'item_kana' => 'Nghỉ không lương',
                'item_ryaku' => 'Nghỉ không lương',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_todoke_kubun',
                'item_cd' => 'OFF3',
                'item_name' => 'Nghỉ đặc biệt có lương',
                'item_kana' => 'Nghỉ đặc biệt có lương',
                'item_ryaku' => 'Nghỉ đặc biệt có lương',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_todoke_kubun',
                'item_cd' => 'OFF4',
                'item_name' => 'Nghỉ thai sản',
                'item_kana' => 'Nghỉ thai sản',
                'item_ryaku' => 'Nghỉ thai sản',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_todoke_kubun',
                'item_cd' => 'OFF5',
                'item_name' => 'Nghỉ nuôi con',
                'item_kana' => 'Nghỉ nuôi con',
                'item_ryaku' => 'Nghỉ nuôi con',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_confirm',
                'item_cd' => '1',
                'item_name' => '未承認',
                'item_kana' => '未承認',
                'item_ryaku' => '未承認',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_confirm',
                'item_cd' => '2',
                'item_name' => '承認済',
                'item_kana' => '承認済',
                'item_ryaku' => '承認済',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_confirm',
                'item_cd' => '3',
                'item_name' => '却下',
                'item_kana' => '却下',
                'item_ryaku' => '却下',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_account_level',
                'item_cd' => '1',
                'item_name' => 'Nhân viên',
                'item_kana' => 'Nhân viên',
                'item_ryaku' => 'Nhân viên',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_account_level',
                'item_cd' => '2',
                'item_name' => 'Leader',
                'item_kana' => 'Leader',
                'item_ryaku' => 'Leader',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_account_level',
                'item_cd' => '3',
                'item_name' => 'Trưởng nhóm',
                'item_kana' => 'Trưởng nhóm',
                'item_ryaku' => 'Trưởng nhóm',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_account_level',
                'item_cd' => '4',
                'item_name' => 'Trưởng phòng',
                'item_kana' => 'Trưởng phòng',
                'item_ryaku' => 'Trưởng phòng',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_account_level',
                'item_cd' => '5',
                'item_name' => 'Trưởng bộ phận',
                'item_kana' => 'Trưởng bộ phận',
                'item_ryaku' => 'Trưởng bộ phận',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_account_level',
                'item_cd' => '6',
                'item_name' => 'Giám đốc',
                'item_kana' => 'Giám đốc',
                'item_ryaku' => 'Giám đốc',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_account_level',
                'item_cd' => '99',
                'item_name' => 'Tổng hợp',
                'item_kana' => 'Tổng hợp',
                'item_ryaku' => 'Tổng hợp',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,

            ],
            [
                'item_group_cd' => 'psj_confirm',
                'item_cd' => '6',
                'item_name' => 'Applying',
                'item_kana' => 'Applying',
                'item_ryaku' => 'Applying',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_sosiki',
                'item_cd' => 'S1_ZENSHA',
                'item_name' => '全社',
                'item_kana' => '全社',
                'item_ryaku' => '全社',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_sosiki',
                'item_cd' => 'S2_HEADOFFICE',
                'item_name' => '本社／支社',
                'item_kana' => '本社／支社',
                'item_ryaku' => '本社／支社',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_sosiki',
                'item_cd' => 'S3_DIVISION',
                'item_name' => '事業部',
                'item_kana' => '事業部',
                'item_ryaku' => '事業部',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_sosiki',
                'item_cd' => 'S4_DEPARTMENT',
                'item_name' => '部',
                'item_kana' => '部',
                'item_ryaku' => '部',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_sosiki',
                'item_cd' => 'S5_GROUP',
                'item_name' => 'グループ',
                'item_kana' => 'グループ',
                'item_ryaku' => 'グループ',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_language',
                'item_cd' => 'ja_JP',
                'item_name' => 'Japanese',
                'item_kana' => 'Japanese',
                'item_ryaku' => 'Japanese',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_language ',
                'item_cd' => 'vi_VN',
                'item_name' => 'VietNamese',
                'item_kana' => 'VietNamese',
                'item_ryaku' => 'VietNamese',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ],
            [
                'item_group_cd' => 'psj_language',
                'item_cd' => 'en_US',
                'item_name' => 'English',
                'item_kana' => 'English',
                'item_ryaku' => 'English',
                'item_kbn_1' => null,
                'item_kbn_2' => null,
                'item_kbn_3' => null,
                'item_kbn_4' => null,
                'item_kbn_5' => null,
                'item_num_1' => null,
                'item_num_2' => null,
                'item_num_3' => null,
                'item_num_4' => null,
                'item_num_5' => null,
                'item_text_1' => null,
                'order_no' => 1,
            ]

        ];
        $table = $this->table('m_items');
        $table->truncate();
        $table->insert($data)->save();
    }
}
