<?php

use Migrations\AbstractSeed;

/**
 * MMenu seed.
 */
class MMenuSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'code' => '1000',
                'name' => 'ダッシュボード',
                'controller' => 'dashboard',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 1,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 2,
                'code' => '1010',
                'name' => 'タイムシート',
                'controller' => 'time_sheet',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 2,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 3,
                'code' => '1011',
                'name' => 'タイムシート登録',
                'controller' => 'time_sheet',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 4,
                'code' => '1020',
                'name' => '届出書',
                'controller' => 'employee_todokes',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 4,
                'function_division' => 1,
                'first_rank' => 3,
                'second_rank' => 3,
                'third_rank' => null,
                'is_menu' => 1
            ],
            [
                'id' => 5,
                'code' => '1021',
                'name' => '届出書-登録',
                'controller' => 'employee_todokes',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 5,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 6,
                'code' => '1022',
                'name' => '届出書-編集',
                'controller' => 'employee_todokes',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 7,
                'code' => '1023',
                'name' => '届出書-詳細',
                'controller' => 'employee_todokes',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 7,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 8,
                'code' => '1030',
                'name' => '残業申請',
                'controller' => 'employee_overtimes',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 8,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 9,
                'code' => '1031',
                'name' => '残業申請-登録',
                'controller' => 'employee_overtimes',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 9,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 10,
                'code' => '1032',
                'name' => '残業申請-編集',
                'controller' => 'employee_overtimes',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 10,
                'function_division' => 0,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 11,
                'code' => '1033',
                'name' => '残業申請-詳細',
                'controller' => 'employee_overtimes',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 11,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 12,
                'code' => '1040',
                'name' => '振替申請',
                'controller' => 'employee_time_transfer',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 12,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 13,
                'code' => '1041',
                'name' => '振替申請-登録',
                'controller' => 'employee_time_transfer',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 13,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 14,
                'code' => '1042',
                'name' => '振替申請-編集',
                'controller' => 'employee_time_transfer',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 14,
                'function_division' => 0,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 15,
                'code' => '1043',
                'name' => '振替申請-詳細',
                'controller' => 'employee_time_transfer',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 14,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 16,
                'code' => '1050',
                'name' => '通知',
                'controller' => 'notices',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 16,
                'function_division' => 0,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 17,
                'code' => '1051',
                'name' => '通知詳細',
                'controller' => 'notices',
                'action' => 'viewNotice',
                'bunrui_no' => 0,
                'order_no' => 17,
                'function_division' => 0,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 18,
                'code' => '1070',
                'name' => 'レポート',
                'controller' => 'report',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 18,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 19,
                'code' => '1071',
                'name' => 'レポート出力',
                'controller' => 'export_excel',
                'action' => 'work_report',
                'bunrui_no' => 0,
                'order_no' => 19,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ], // end group 1


            [
                'id' => 20,
                'code' => '2010',
                'name' => 'タイムシート承認',
                'controller' => 'work',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 1,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 21,
                'code' => '2020',
                'name' => '承認一覧',
                'controller' => 'judgements',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 2,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 22,
                'code' => '2021',
                'name' => '届書の承認',
                'controller' => 'judgements',
                'action' => 'view_employee_todoke',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 23,
                'code' => '2022',
                'name' => '残業の承認',
                'controller' => 'judgements',
                'action' => 'view_employee_overtime',
                'bunrui_no' => 0,
                'order_no' => 4,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 24,
                'code' => '2023',
                'name' => '振替の承認',
                'controller' => 'judgements',
                'action' => 'view_time_transfer',
                'bunrui_no' => 0,
                'order_no' => 5,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],




            // end group 2

            [
                'id' => 25,
                'code' => '3010',
                'name' => '企業',
                'controller' => 'companies',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 1,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 26,
                'code' => '3011',
                'name' => '企業-詳細',
                'controller' => 'companies',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 2,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 27,
                'code' => '3012',
                'name' => '企業-木分け-詳細',
                'controller' => 'companies',
                'action' => 'companies_tree_view',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 28,
                'code' => '3013',
                'name' => '企業-編集',
                'controller' => 'companies',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 4,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 29,
                'code' => '3014',
                'name' => '企業-部門',
                'controller' => 'companies',
                'action' => 'view_depanies',
                'bunrui_no' => 0,
                'order_no' => 5,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 30,
                'code' => '3015',
                'name' => '企業-部門-編集',
                'controller' => 'company_sections',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 31,
                'code' => '3016',
                'name' => '企業-部門-削除',
                'controller' => 'companies',
                'action' => 'delete_section',
                'bunrui_no' => 0,
                'order_no' => 7,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 32,
                'code' => '3020',
                'name' => 'グループ管理',
                'controller' => 'group_confirms',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 8,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 33,
                'code' => '3021',
                'name' => 'グループ管理-登録',
                'controller' => 'group_confirms',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 9,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 34,
                'code' => '3022',
                'name' => 'グループ管理-編集',
                'controller' => 'group_confirms',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 10,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 35,
                'code' => '3023',
                'name' => 'グループ管理-詳細',
                'controller' => 'group_confirms',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 11,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 36,
                'code' => '3030',
                'name' => '地区',
                'controller' => 'areas',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 12,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 37,
                'code' => '3031',
                'name' => '地区-登録',
                'controller' => 'areas',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 13,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 38,
                'code' => '3032',
                'name' => '地区-編集',
                'controller' => 'areas',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 14,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 39,
                'code' => '3033',
                'name' => '地区-詳細',
                'controller' => 'areas',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 15,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 40,
                'code' => '3040',
                'name' => 'シフト',
                'controller' => 'shift_timeable',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 16,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 41,
                'code' => '3041',
                'name' => 'シフト‐登録',
                'controller' => 'shift_timeable',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 17,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 42,
                'code' => '3042',
                'name' => 'シフト‐編集',
                'controller' => 'shift_timeable',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 18,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 43,
                'code' => '3043',
                'name' => 'シフト‐詳細',
                'controller' => 'shift_timeable',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 19,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 44,
                'code' => '3050',
                'name' => 'お知らせ',
                'controller' => 'm_notices',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 20,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 45,
                'code' => '3051',
                'name' => 'お知らせ‐登録',
                'controller' => 'm_notices',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 21,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 46,
                'code' => '3052',
                'name' => 'お知らせ‐編集',
                'controller' => 'm_notices',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 22,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 47,
                'code' => '3053',
                'name' => 'お知らせ‐詳細',
                'controller' => 'm_notices',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 23,
                'function_division' => 3,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ], // end group 3
            [
                'id' => 48,
                'code' => '4010',
                'name' => '人事マスタ',
                'controller' => 'employees',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 1,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 49,
                'code' => '4011',
                'name' => '人事マスタ‐登録',
                'controller' => 'employees',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 2,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 50,
                'code' => '4012',
                'name' => '人事マスタ‐編集',
                'controller' => 'employees',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 51,
                'code' => '4013',
                'name' => '人事マスタ‐詳細',
                'controller' => 'employees',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 4,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 52,
                'code' => '4020',
                'name' => '人事シフト',
                'controller' => 'employee_timeable',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 5,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 53,
                'code' => '4021',
                'name' => '人事シフト‐登録',
                'controller' => 'employee_timeable',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 54,
                'code' => '4022',
                'name' => '人事シフト‐編集',
                'controller' => 'employee_timeable',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 7,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 55,
                'code' => '4023',
                'name' => '人事シフト‐詳細',
                'controller' => 'employee_timeable',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 8,
                'function_division' => 4,
                'first_rank' => 1,
                'second_rank' => 1,
                'third_rank' => null,
                'is_menu' => 0
            ],
            [
                'id' => 56,
                'code' => '4030',
                'name' => '有休付与計算',
                'controller' => 'employee_earn_day_offs',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 9,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 57,
                'code' => '4031',
                'name' => '有休付与計算‐出力',
                'controller' => 'employee_earn_day_offs',
                'action' => 'export',
                'bunrui_no' => 0,
                'order_no' => 10,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 58,
                'code' => '4040',
                'name' => '有休付与設定',
                'controller' => 'day_off_settings',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 11,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 59,
                'code' => '4050',
                'name' => '36協定設定',
                'controller' => 'kyoutei_overtimes',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 12,
                'function_division' => 4,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ], //end group 4
            [
                'id' => 60,
                'code' => '5010',
                'name' => '案件実績',
                'controller' => 'project_timesheets',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 1,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 61,
                'code' => '5011',
                'name' => '案件実績‐登録',
                'controller' => 'project_timesheets',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 2,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 62,
                'code' => '5020',
                'name' => '案件実績承認',
                'controller' => 'project_timesheet_confirms',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 63,
                'code' => '5030',
                'name' => '取引先',
                'controller' => 'clients',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 4,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 64,
                'code' => '5031',
                'name' => '取引先‐登録',
                'controller' => 'clients',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 5,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 65,
                'code' => '5032',
                'name' => '取引先‐編集',
                'controller' => 'clients',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 66,
                'code' => '5033',
                'name' => '取引先‐詳細',
                'controller' => 'clients',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 7,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 67,
                'code' => '5040',
                'name' => '案件管理',
                'controller' => 'projects',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 8,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 68,
                'code' => '5041',
                'name' => '案件‐登録',
                'controller' => 'projects',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 9,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 69,
                'code' => '5042',
                'name' => '案件‐編集',
                'controller' => 'projects',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 10,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 70,
                'code' => '5043',
                'name' => '案件‐詳細',
                'controller' => 'projects',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 11,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 71,
                'code' => '5044',
                'name' => '案件‐帳票出力',
                'controller' => 'projects',
                'action' => 'report',
                'bunrui_no' => 0,
                'order_no' => 12,
                'function_division' => 5,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ], // end group 5

            [
                'id' => 72,
                'code' => '6010',
                'name' => '休日管理',
                'controller' => 'm_holidays',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 1,
                'function_division' => 6,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 73,
                'code' => '6011',
                'name' => '休日管理‐登録',
                'controller' => 'm_holidays',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 2,
                'function_division' => 6,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 74,
                'code' => '6020',
                'name' => 'メニューメンテ',
                'controller' => 'menus',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 6,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 75,
                'code' => '6030',
                'name' => '権限メンテ',
                'controller' => 'kengens',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 4,
                'function_division' => 6,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 76,
                'code' => '6040',
                'name' => 'システム設定メンテ',
                'controller' => 'system_settings',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 5,
                'function_division' => 6,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 77,
                'code' => '6050',
                'name' => '名称グループ項目',
                'controller' => 'item_kanri',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 6,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 78,
                'code' => '6051',
                'name' => '名称項目',
                'controller' => 'items',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 7,
                'function_division' => 6,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ], // end group 6
            [
                'id' => 79,
                'code' => '7010',
                'name' => 'ログイン',
                'controller' => 'login',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 1,
                'function_division' => 7,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 80,
                'code' => '7011',
                'name' => 'ログアウト',
                'controller' => 'logout',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 2,
                'function_division' => 7,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 81,
                'code' => '7020',
                'name' => 'プロフィール',
                'controller' => 'profile',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 7,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 82,
                'code' => '7020',
                'name' => 'プロフィール',
                'controller' => 'm_holidays',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 7,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 83,
                'code' => '7020',
                'name' => 'Report Day Off',
                'controller' => 'report_day_off',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 84,
                'code' => '7020',
                'name' => 'Report Day Off',
                'controller' => 'report_day_off',
                'action' => 'dayOffReport',
                'bunrui_no' => 0,
                'order_no' => 3,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 85,
                'code' => '1060',
                'name' => 'Đổi giờ làm',
                'controller' => 'employee_change_shift',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 15,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 86,
                'code' => '1061',
                'name' => 'Đăng ký đổi giờ làm',
                'controller' => 'employee_change_shift',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 16,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 87,
                'code' => '1062',
                'name' => 'Sửa đăng ký đổi giờ làm',
                'controller' => 'employee_change_shift',
                'action' => 'edit',
                'bunrui_no' => 0,
                'order_no' => 17,
                'function_division' => 0,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 88,
                'code' => '1063',
                'name' => 'Chi tiết đăng ký đổi giờ làm',
                'controller' => 'employee_change_shift',
                'action' => 'view',
                'bunrui_no' => 0,
                'order_no' => 18,
                'function_division' => 1,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 89,
                'code' => '2024',
                'name' => 'Chi tiết đăng ký đổi giờ làm',
                'controller' => 'judgements',
                'action' => 'view_shift_change',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
            [
                'id' => 90,
                'code' => '2030',
                'name' => 'Bảng chấm công',
                'controller' => 'todoke_report',
                'action' => 'index',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 1
            ],
            [
                'id' => 91,
                'code' => '2030',
                'name' => '有休付与計算',
                'controller' => 'employee_earn_day_offs',
                'action' => 'add',
                'bunrui_no' => 0,
                'order_no' => 6,
                'function_division' => 2,
                'first_rank' => 0,
                'second_rank' => 0,
                'third_rank' => 0,
                'is_menu' => 0
            ],
        ];
        $table = $this->table('m_menus');
        $table->truncate();
        $table->insert($data)->save();
    }
}
