<?php


use Phinx\Seed\AbstractSeed;

class CompanySectionSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $data = [
            [
                'company_id' => 1,
                'name' => '全社',
                'parent_id' => null,
                'section_type' => null,
                'section_code' => 'ZA',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => 'ソリューション事業部門',
                'parent_id' => 1,
                'section_type' => null,
                'section_code' => 'A01',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => '',
            ],
            [
                'company_id' => 1,
                'name' => 'ソリューション事業部',
                'parent_id' => 2,
                'section_type' => null,
                'section_code' => '1000',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => '１部１Grp',
                'parent_id' => 6,
                'section_type' => null,
                'section_code' => '11001',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => '',
            ],
            [
                'company_id' => 1,
                'name' => '１部２Grp',
                'parent_id' => 6,
                'section_type' => null,
                'section_code' => '11002',
                'tel' => '84937917030',
                'fax' => '937917030',
                'url' => null,
                'zipcode' => '',
                'address' => 'So 1, Pham Huy Thong, Ngoc Khanh, Ba Dinh',
                'memo' => 'て',
            ],
            [
                'company_id' => 1,
                'name' => 'ソリューション第１部',
                'parent_id' => 3,
                'section_type' => null,
                'section_code' => '1100',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => 'ソリューション第2部',
                'parent_id' => 3,
                'section_type' => null,
                'section_code' => '1200',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => 'システム開発事業部',
                'parent_id' => 2,
                'section_type' => null,
                'section_code' => '3000',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => '開発第１部',
                'parent_id' => 8,
                'section_type' => null,
                'section_code' => '3100',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => '開発第２部',
                'parent_id' => 8,
                'section_type' => null,
                'section_code' => '3200',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => '事業推進部',
                'parent_id' => 2,
                'section_type' => null,
                'section_code' => '4000',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => '経営企画本部',
                'parent_id' => 1,
                'section_type' => null,
                'section_code' => 'A02',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => '経営企画部',
                'parent_id' => 80,
                'section_type' => null,
                'section_code' => '5000',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
            [
                'company_id' => 1,
                'name' => '人材開発室',
                'parent_id' => 80,
                'section_type' => null,
                'section_code' => '6000',
                'tel' => '',
                'fax' => '',
                'url' => null,
                'zipcode' => '',
                'address' => '',
                'memo' => null,
            ],
        ];
        $table=$this->table('company_sections');
        $table->truncate();
        $table->insert($data)->save();
    }
}
